version: "3"
services:
  api-database:
    image: postgres
    container_name: "api-database"
    env_file:
      - postgres.env # configure postgres
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379